// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fejnlotarqmhsqeyvdtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlam5sb3RhcnFtaHNxZXl2ZHR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Mjk0NDYsImV4cCI6MjA1OTQwNTQ0Nn0.48-oiycXHvdd9wyVeTYttWnU_5YerHlm0jZJPVTp6p0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);